### ISSUE TITLE
Problems about Double Precision

### ISSUE THREAD

**Issue by jiangshibiao** [laser-ufpb/VRPTWController#4]
I want to point out that the **verification method in this code has a bug**, and I also give two possible suggestions to fix it.

## where is the bug

The rule says that _Matrix D containing the distances and times is obtained from the location coordinates, by computing the Euclidean distances truncated to one decimal place_.
However, the program fails to contain the precise number after conversion to binary internally **(e.g. 0.1-->0.000110011)**. As a result, it's very dangerous if you use C++ to compare two real numbers directly. The core VRPTWController code is as follows.

```C++
travelTime = max(travelTime + edgeCost + (double) instance->s[route.at(i - 1)], (double) instance->l[route.at(i)]);
// std::cout << "("<< route.at(i - 1) << "," << route.at(i) << ") c" << edgeCost << " t" << travelTime << std::endl;
if(travelTime > instance->u[route.at(i)]) { // checks TW violation
    std::cout << "TW of " << route.at(i) << " ([" << instance->l[route.at(i)] 
        << "," << instance->u[route.at(i)] << "]) was violated (arrival time = " << travelTime << ")" << std::endl;
    return false;
}
```

And now I give a specific case that is wrongly judged by this code. In instance `Homberger/C1_2_8.TXT`, my algorithm produces a valid route `[0, 155, 78, 175, 119, 166, 35, 126, 71, 9, 1, 99, 53, 0]` but is warning by the message **TW of 126 ([399,609]) was violated (arrival time = 609)**. Then I checked each step in this route:

```
155 ( 14, 272, 90)   dis: (14.7648230602, 14.7)   arrive:  (14.7000000000000, 14.7)    after service: (104.7000000000000, 104.7)
 78 ( 53, 350, 90)   dis: ( 1.4142135624,  1.4)   arrive: (106.1000000000000, 106.1)   after service: (196.1000000000000, 196.1)
175 (168, 422, 90)   dis: ( 4.1231056256,  4.1)   arrive: (200.2000000000000, 200.2)   after service: (290.2000000000000, 290.2)
119 (107, 341, 90)   dis: (38.5875627631, 38.5)   arrive: (328.7000000000000, 328.7)   after service: (418.7000000000000, 418.7)
166 (177, 456, 90)   dis: ( 3.1622776602,  3.1)   arrive: (421.8000000000001, 421.8)   after service: (511.8000000000001, 511.8)
 35 (289, 531, 90)   dis: ( 3.6055512755,  3.6)   arrive: (515.4000000000001, 515.4)   after service: (605.4000000000001, 605.4)
126 (399, 609, 90)   dis: ( 3.6055512755,  3.6)   arrive: (609.0000000000001, 609.0)   after service: (699.0000000000001, 699.0)
```

The first number in `arrive/after service` is calculated by direct `double` operations in C++, similar to VRPTWController (print 13 digits after the decimal point). The second number in `arrive/after service` is the precise number. **It's clear that the judge mistakenly thinks that the arrival time at `126` is 609.0000000000001 which is larger than the limitation `609`.**

## suggestions to fix the problem

1. One simple but risky way is: add a traditional **EPS** trick in the code.  i.e., replace the code `if(travelTime > instance->u[route.at(i)])` with `if(travelTime > instance->u[route.at(i)]) + EPS`. Arbitrary setting in this problem (e.g. `EPS=1e-9` or `EPS=1e-6`) is enough to fix the bug, because all the real numbers only have one digit after the decimal point.
2. There is another way that can fix this bug **completely** with more modification. This VRPTWController can always contain integers instead of real numbers. i.e., multiply each number by 10, and use integer comparison everywhere.

**Comment by EduardoQueiroga** [comment]
Thank you for your contribution. It was fixed using an EPS of 1e-6.
